require "rake"
require_relative "../Rakefile_common.rb"

task :default => [:install_osx] do
end

desc "install 3rd parties for OSX"
task :install_osx do
  FileUtils.cd "Eigen"
  sh "rake install_osx"
  FileUtils.cd ".."
end

desc "install 3rd parties for LINUX"
task :install_linux do
  FileUtils.cd "Eigen"
  sh "rake install_linux"
  FileUtils.cd ".."
end

desc "install 3rd parties for WINDOWS"
task :install_win, [:year, :bits] do |t,args|
  args.with_defaults(:year => "2017", :bits => "x64" )
  FileUtils.cd "Eigen"
  sh "rake install_win[#{args.year},#{args.bits}]"
  FileUtils.cd ".."
  FileUtils.mkdir_p "../lib3rd/include"
  FileUtils.mkdir_p "../lib3rd/lib"
  FileUtils.mkdir_p "../lib3rd/dll"
  FileUtils.cp "zlib/include/zlib.h",      "../lib3rd/include"
  FileUtils.cp "zlib/include/zconf.h",     "../lib3rd/include"
  FileUtils.cp "zlib/bin/zlib.dll",        "../lib3rd/dll"
  FileUtils.cp "zlib/lib/zlibd.lib",       "../lib3rd/lib"
  FileUtils.cp "zlib/bin/zlibd.dll",       "../lib3rd/dll"
  FileUtils.cp "zlib/lib/zlibd.lib",       "../lib3rd/lib"
  FileUtils.cp "zlib/lib/zlibstatic.lib",  "../lib3rd/lib"
  FileUtils.cp "zlib/lib/zlibstaticd.lib", "../lib3rd/lib"
end

desc "clean 3rd parties for OSX"
task :clean_osx do
  FileUtils.cd "Eigen"
  sh "rake clean_osx"
  FileUtils.cd ".."
end

desc "clean 3rd parties for LINUX"
task :clean_linux do
  FileUtils.cd "Eigen"
  sh "rake clean_linux"
  FileUtils.cd ".."
end

desc "clean 3rd parties for WINDOWS"
task :clean_win do
  FileUtils.cd "Eigen"
  sh "rake clean_win"
  FileUtils.cd ".."
end
