require "rake"
require "fileutils"

require_relative "../../Rakefile_common.rb"

VER = "3.4.0"

desc "install Eigen3"
task :install do
  if File.exist?("eigen-#{VER}.zip") then
  else
    url_download( "https://gitlab.com/libeigen/eigen/-/archive/#{VER}/eigen-#{VER}.zip", "eigen-#{VER}.zip" )
  end
  if Dir.exist?("eigen-#{VER}/Eigen") then
  else
    extract_zip("eigen-#{VER}.zip");
  end
  FileUtils.cp_r "eigen-#{VER}/Eigen", '../../src'
end

task :install_osx => :install do
end

task :install_linux => :install do
end

task :install_win => :install do
end

task :clean_osx do
end

task :clean_linux do
end

task :clean_win do
end
